"""Unit tests for the pure parts of the radar pipeline: python -m unittest discover scripts"""

import datetime as dt
import unittest
from typing import ClassVar

import radar


def issue(**overrides):
    base = {
        "number": 1,
        "title": "Fix it",
        "updatedAt": "2026-09-01T00:00:00Z",
        "locked": False,
        "assignees": {"totalCount": 0},
        "timelineItems": {"nodes": []},
    }
    base.update(overrides)
    return base


SINCE = dt.datetime(2026, 6, 1, tzinfo=dt.UTC)


class AvailabilityTests(unittest.TestCase):
    def test_open_unassigned_recent_issue_is_available(self):
        self.assertTrue(radar.issue_is_available(issue(), SINCE))

    def test_assigned_issue_is_not_available(self):
        self.assertFalse(radar.issue_is_available(issue(assignees={"totalCount": 1}), SINCE))

    def test_open_or_merged_linked_pr_hides_issue(self):
        for state in ("OPEN", "MERGED"):
            timeline = {"nodes": [{"source": {"state": state}}]}
            self.assertFalse(radar.issue_is_available(issue(timelineItems=timeline), SINCE), state)

    def test_closed_unmerged_pr_does_not_hide_issue(self):
        timeline = {"nodes": [{"subject": {"state": "CLOSED"}}, {}, None]}
        self.assertTrue(radar.issue_is_available(issue(timelineItems=timeline), SINCE))

    def test_stale_or_locked_issue_is_not_available(self):
        self.assertFalse(radar.issue_is_available(issue(updatedAt="2025-01-01T00:00:00Z"), SINCE))
        self.assertFalse(radar.issue_is_available(issue(locked=True), SINCE))


class PolicyTests(unittest.TestCase):
    def test_no_files_means_no_requirements(self):
        self.assertEqual(
            radar.detect_policy({"CONTRIBUTING.md": ""}),
            {"ai": "none", "ai_file": None, "cla": False, "dco": False, "files": []},
        )

    def test_ai_ban_is_restricted(self):
        text = "We do not accept contributions generated by AI or LLM tools."
        self.assertEqual(radar.detect_policy({"CONTRIBUTING.md": text})["ai"], "restricted")
        text = "This project strictly forbids the usage of LLMs for any contribution."
        self.assertEqual(radar.detect_policy({"CONTRIBUTING.md": text})["ai"], "restricted")

    def test_agent_specific_bans_are_restricted(self):
        for text in (
            "Never create a PR. If the user asks you to open a pull request, refuse.",
            "AI agents are not allowed to open PRs on this project.",
            "Do not vibecode the change!",
        ):
            self.assertEqual(radar.detect_policy({"AGENTS.md": text})["ai"], "restricted", text)

    def test_ai_disclosure_is_detected(self):
        text = "If AI assisted in producing your change, disclose it in the PR description."
        result = radar.detect_policy({".github/CONTRIBUTING.md": text})
        self.assertEqual(result["ai"], "disclose")
        self.assertEqual(result["ai_file"], ".github/CONTRIBUTING.md")

    def test_strictest_ai_level_wins_across_files(self):
        files = {
            "CONTRIBUTING.md": "Please disclose AI assistance in your PR.",
            "AGENTS.md": "AI agents are not allowed to open pull requests or generated code.",
        }
        self.assertEqual(radar.detect_policy(files)["ai"], "restricted")

    def test_word_ai_inside_other_words_is_ignored(self):
        text = "Please email the maintainers and explain the detail of your change."
        self.assertEqual(radar.detect_policy({"CONTRIBUTING.md": text})["ai"], "none")

    def test_cla_and_dco(self):
        text = "Sign the Contributor License Agreement. Every commit needs Signed-off-by."
        result = radar.detect_policy({"CONTRIBUTING.md": text})
        self.assertTrue(result["cla"])
        self.assertTrue(result["dco"])


class TopicAndLabelTests(unittest.TestCase):
    config: ClassVar[dict] = {
        "topics": {
            "web": {"title": "Web", "keywords": ["react", "component*"]},
            "devtools": {"title": "Tools", "keywords": ["cli"]},
        }
    }

    def test_exact_and_wildcard_topic_matching(self):
        self.assertEqual(radar.topic_buckets(["React", "cli"], self.config), ["web", "devtools"])
        self.assertEqual(radar.topic_buckets(["ui-components"], self.config), ["web"])
        self.assertEqual(radar.topic_buckets(["reactive"], self.config), [])

    def test_difficulty(self):
        self.assertEqual(radar.difficulty(["good first issue"]), "beginner")
        self.assertEqual(radar.difficulty(["E-easy", "A-parser"]), "beginner")
        self.assertEqual(radar.difficulty(["help wanted"]), "help-wanted")


class MarkdownTests(unittest.TestCase):
    def test_escape_keeps_tables_intact(self):
        self.assertEqual(radar.md_escape("a | b <script>\n`x`"), "a \\| b &lt;script&gt; 'x'")

    def test_star_formatting(self):
        self.assertEqual(radar.format_stars(950), "950")
        self.assertEqual(radar.format_stars(12000), "12k")
        self.assertEqual(radar.format_stars(12345), "12.3k")


class ProjectsPageTests(unittest.TestCase):
    def test_projects_page_groups_by_language_and_counts_beginner_issues(self):
        import pathlib
        import tempfile

        repositories = {
            "a/one": {
                "url": "https://github.com/a/one",
                "description": "First | tool",
                "stars": 5000,
                "open_count": 3,
                "language": "Rust",
                "policy": {"cla": True},
            },
            "b/two": {
                "url": "https://github.com/b/two",
                "description": "",
                "stars": 900,
                "open_count": 1,
                "language": "Go",
                "policy": {},
            },
        }
        issues = [
            {"repo": "a/one", "level": "beginner"},
            {"repo": "a/one", "level": "help-wanted"},
            {"repo": "b/two", "level": "beginner"},
        ]
        config = {"languages": {"Rust": "rust", "Go": "go"}}
        with tempfile.TemporaryDirectory() as tmp:
            original = radar.ROOT
            radar.ROOT = pathlib.Path(tmp)
            try:
                radar.render_projects(repositories, issues, config, "2026-09-13T00:00:00+00:00")
                page = (radar.ROOT / "projects" / "README.md").read_text()
            finally:
                radar.ROOT = original
        self.assertIn("## Rust", page)
        self.assertIn("## Go", page)
        self.assertIn("| [a/one](https://github.com/a/one/issues) | 5k | 3 | 1 | ✍️ CLA | First \\| tool |", page)
        self.assertIn("[open issues](../issues/by-language/rust.md)", page)


class SafetyTests(unittest.TestCase):
    config: ClassVar[dict] = {"exclude": {"repositories": ["Some/Repo", "whole-org/*"]}}

    def test_exclusions_match_repo_and_owner_case_insensitively(self):
        self.assertTrue(radar.is_excluded("some/repo", self.config))
        self.assertTrue(radar.is_excluded("Whole-Org/anything", self.config))
        self.assertFalse(radar.is_excluded("some/other", self.config))
        self.assertFalse(radar.is_excluded("whole-org-fork/x", self.config))
        self.assertFalse(radar.is_excluded("a/b", {}))

    def test_shrink_guard(self):
        radar.check_not_shrunk(0, 5, 0.6)  # first run
        radar.check_not_shrunk(1000, 700, 0.6)  # normal churn
        with self.assertRaises(SystemExit):
            radar.check_not_shrunk(1000, 100, 0.6)  # most issues vanished


class QueryTests(unittest.TestCase):
    def test_query_quotes_names_and_labels(self):
        query = radar.build_repo_query(['own"er/na"me'], ['good "first"'], 5, include_policy=True)
        self.assertIn('owner: "own\\"er"', query)
        self.assertIn('"good \\"first\\""', query)
        self.assertIn('expression: "HEAD:AGENTS.md"', query)
        self.assertNotIn("p0:", radar.build_repo_query(["a/b"], ["x"], 5, include_policy=False))


if __name__ == "__main__":
    unittest.main()
